[project]
name = "cookiecutter-data-science"
version = "0.1.0"
description = "Repositório dedicado a criar formatos padronizados de projetos de Data Science"
readme = "README.md"
dependencies = [
    "cookiecutter>=2.6.0",
]

